ktor:
    application:
        modules:
            - com.eniobiondic.noted.ApplicationKt.module
    deployment:
        port: 8888

# local database configuration for testing
database:
    connection: "jdbc:postgresql://localhost:5432/noted"
    username: "postgres"
    password: "postgres"
    poolSize: 5